// GENERATED by efyv-nodegen from node/pages.py — DO NOT EDIT.
// Change the node's pages and run `efyv-nodegen gen`.
'use client';

import { MakerStudio } from '@efyv/maker';
import type { MakerStudioSpec } from '@efyv/maker';

const SPEC: MakerStudioSpec = {
  "schema_version": 1,
  "document": {
    "kind": "efyv-labymake-project",
    "autosave": true,
    "versioning": true,
    "initial": {
      "name": "labymake-project",
      "canvasWidth": 1,
      "canvasHeight": 1,
      "targetAssetType": "EFYVSprite",
      "assetProperties": {
        "entityName": "labymake-project"
      },
      "animations": [
        {
          "stateName": "Idle",
          "fps": 12,
          "frames": [
            {
              "durationMs": 83,
              "layers": [
                {
                  "isVisible": true,
                  "opacity": 1,
                  "rgbaBytes": "AAAAAA=="
                }
              ]
            }
          ]
        }
      ]
    },
    "schema": {},
    "validator": null
  },
  "workspace": {
    "kind": "canvas",
    "selection": "pixel-layer-frame",
    "width_field": "canvasWidth",
    "height_field": "canvasHeight",
    "animations_field": "animations"
  },
  "panels": [
    {
      "kind": "history"
    },
    {
      "kind": "jobs"
    },
    {
      "kind": "artifacts",
      "destination": {
        "kind": "browser-folder",
        "fallback": "zip"
      }
    },
    {
      "kind": "code",
      "language": "json",
      "read only": true,
      "field": null
    }
  ],
  "tools": [
    {
      "kind": "tool",
      "id": "select",
      "label": "Select",
      "options": {}
    },
    {
      "kind": "tool",
      "id": "pencil",
      "label": "Pencil",
      "options": {
        "size": 1
      }
    },
    {
      "kind": "tool",
      "id": "eraser",
      "label": "Eraser",
      "options": {
        "size": 1
      }
    },
    {
      "kind": "tool",
      "id": "fill",
      "label": "Fill",
      "options": {}
    },
    {
      "kind": "tool",
      "id": "eyedropper",
      "label": "Eyedropper",
      "options": {}
    },
    {
      "kind": "tool",
      "id": "shape",
      "label": "Shape",
      "options": {}
    }
  ],
  "commands": [
    {
      "kind": "command",
      "id": "validate",
      "label": "Validate asset",
      "operation": "labymake-engine.validate",
      "input": {
        "snapshotJson": {
          "from": "$document",
          "encoding": "base64-json"
        }
      },
      "result": null,
      "confirmation": null
    },
    {
      "kind": "command",
      "id": "export",
      "label": "Export for Unity",
      "operation": "labymake-engine.export",
      "input": {
        "snapshotJson": {
          "from": "$document",
          "encoding": "base64-json"
        }
      },
      "result": "application/zip",
      "confirmation": null
    }
  ],
  "jobs": [],
  "artifacts": [
    {
      "kind": "image/png",
      "extension": ".png"
    },
    {
      "kind": "application/x-efyvlaby",
      "extension": ".efyvlaby"
    },
    {
      "kind": "application/zip",
      "extension": ".zip"
    }
  ],
  "sources": [],
  "style": null,
  "browser_handoff": true
};

export default function StudioPage() {
  return <MakerStudio pageKey={"studio"} title={"Labyrinth asset studio"} spec={SPEC} />;
}
