# GENERATED by efyv-nodegen from node/topology.py — DO NOT EDIT.
# The v1 topology view (SERVICES + BUILD_CONTEXTS) that cluster_config.py, the node's
# infra/config/render.py, and EFYV-CI's importlib readers consume. Plain stdlib dict
# literals, so a bare interpreter imports it. Change node/topology.py and run
# `efyv-nodegen manifest`.
from __future__ import annotations

SERVICES: dict[str, dict] = {
    "frontend": {"port": 3210, "depends_on": {"backend": "healthy"}},
    "backend": {"port": 8000, "depends_on": {"postgres": "healthy", "redis": "healthy", "compute": "healthy"}},
    "compute": {"port": 9000, "depends_on": {}},
    "postgres": {"port": 5432, "depends_on": {}},
    "redis": {"port": 6379, "depends_on": {}},
    "labymake-engine": {"port": 50051, "depends_on": {}},
}

BUILD_CONTEXTS: dict[str, str] = {
    "labymake-engine": "services/labymake-engine",
}
