// GENERATED by efyv-nodegen from app.efyv screens — DO NOT EDIT.
// Change the node's screens and regenerate.

export interface NavItem {
  key: string;
  label: string;
  href: string;
  icon: string;
}

export const NAV_ITEMS: NavItem[] = [
];
