// GENERATED by efyv-nodegen from app.efyv screens + brand — DO NOT EDIT.
// Change the node's screens/brand and regenerate.
'use client';

import { AppShell, Brand } from '@efyv/ui';
import type { OperatorLink } from '@efyv/ui';
import { useAuth } from '@efyv/core';
import { usePathname } from 'next/navigation';
import type { ReactNode } from 'react';

import { NAV_ITEMS } from '../nav.generated';

const OPERATOR_LINKS: OperatorLink[] = [];

export default function DashboardLayout({ children }: { children: ReactNode }) {
  const { context, pageAvailable, signOut } = useAuth();
  const currentPath = usePathname();
  const user = context?.user;
  return (
    <AppShell
      nav={NAV_ITEMS}
      canAccess={pageAvailable}
      currentPath={currentPath}
      brand={<Brand label="EFYV LabyMake" icon="grid-3x3" gradient={["#22c55e", "#0f766e"] as const} href="/dashboard" />}
      operatorLinks={OPERATOR_LINKS}
      account={user ? { name: user.fullName || user.email, email: user.email, roleLabel: user.role, onSignOut: () => { void signOut(); } } : undefined}
    >
      {children}
    </AppShell>
  );
}
